### ISSUE TITLE
[en] `so_5::message_t` is optional in some places, and mandatory in the others?

### ISSUE THREAD

**Issue by basiliscos** [eao197/so-5-5#23]
Hi,

If I define message user-defined struct, i.e. 

```cpp

struct timeout_initialize {
    actor_t actor;
    so_5::mbox_t mbox;
    timeout_initialize(actor_t actor_, const so_5::mbox_t& mbox_): actor{actor_}, mbox{mbox_}{}
};
```

it is still possible to send it via `so_5::send<timeout_initialize>(...)`. However, when I try to send it via `schedule_timer`

```cpp
so_environment().schedule_timer(
                std::make_unique< message::timeout_initialize >(m.actor, m.mbox ),
                so_direct_mbox(),
                std::chrono::milliseconds(200),
                std::chrono::milliseconds::zero()
    );
```

the compiler errors with :

```
../so_5/rt/h/message.hpp:655:18: error: static assertion failed: expected a type derived from the message_t
   static_assert( is_classical_message< Msg >::value,
```

If the  `timeout_initialize` inherits from `so_5::message_t`, the error message disappears and everything looks fine. 

However, it's a bit weird API-interface: messages, which I don't need send via `schedule_timer` can be user-defined types, but if they are delivered via `schedule_timer`, they have to be derived from ` so_5::message_t` .

**Comment by eao197** [comment]
It is because of historical reasons: in the first versions of SO-5 there were only messages derived from `so_5::message_t` and there weren't `send` functions. Then `send` functions were added and `schedule_timer` became less useful. And then the possibility to send an user-type message was introduced. But under the hood an user-type message is converted into special instance of `so_5::message_t`. Only this instance can be passed to `schedule_timer`, because of that there is a static assert in implementation of `schedule_timer`.

The only valid way to send a periodic or delayed message of an user type is to use `send_periodic` or `send_delayed` function. So you have to write:
```cpp
auto timer_id =  so_5::send_periodic< message::timeout_initialize >(
   so_environment(),
   so_direct_mbox(),
   std::chrono::milliseconds(200),
   std::chrono::milliseconds::zero(),
   m.actor,
   m.mbox );
```
Or, if you want to send a message to your agent:
```cpp
auto timer_id =  so_5::send_periodic< message::timeout_initialize >(
   *this, // environment and direct-mbox will be detected automatically.
   std::chrono::milliseconds(200),
   std::chrono::milliseconds::zero(),
   m.actor,
   m.mbox );
```
And important notice: in SO-5.6 there won't be public `schedule_timer` method in `environment_t`. The only way of sending messages (regardless of their type) will be `send`-functions (e.g. `send`, `send_delayed` and `send_periodic`).

**Comment by basiliscos** [comment]
okay, got it.

> The only valid way to send a periodic or delayed message of an user type is to use send_periodic or send_delayed function

would it be possible to `send_delayed` return `timer_id` ? Now it returns `void`, so no way to cancel. It is possible to use `send_periodic`  function, but I bet the code will be confusing & not self-explaining then.

**Comment by eao197** [comment]
> would it be possible to send_delayed return timer_id ?

At the current moment: no.
Delayed messages those can be safely and guaranteed cancelled is a hard topic. It is more or less explained [here](https://sourceforge.net/p/sobjectizer/wiki/so5extra%201.2%20Revocable%20Timers/).

**Comment by basiliscos** [comment]
Thanks for explanations!
