### ISSUE TITLE
[en] timertt docfix suggestion

### ISSUE THREAD

**Issue by prayforwind** [eao197/so-5-5#27]
1. "when there is no timers" --> "when there is no expired timers"
2. "m_whan" --> "m_when"
: )

**Comment by eao197** [comment]
> "when there is no timers" --> "when there is no expired timers"

I think the source form is right: the timer wheel mechanism consumes some resources even if there are no timers at all (waiting or already expired). Two other types of timer mechanisms (timer heap and timer list) consume resources only if there are waiting timers. Expired timers are removed from timer mechanisms and aren't taken into account anymore (regardless of a mechanism type).

> "m_whan" --> "m_when"

Thanks. I've fixed in in [timertt's repository on SourceForge](https://sourceforge.net/p/sobjectizer/repo/HEAD/tree/branches/timertt/1.2/dev/timertt/all.hpp). This fix will be a part of the next timertt update.

**Comment by prayforwind** [comment]
> > "when there is no timers" --> "when there is no expired timers"
> 
> I think the source form is right: the timer wheel mechanism consumes some resources even if there are no timers at all (waiting or already expired). Two other types of timer mechanisms (timer heap and timer list) consume resources only if there are waiting timers. Expired timers are removed from timer mechanisms and aren't taken into account anymore (regardless of a mechanism type).

Thanks for the correct expression "waiting or already expired". Not just "expired".

I still think the timer wheel mechanism consumes no resources when there are no timers at all (waiting or already expired). 
Because
details::thread_impl_template::sleep_for_next_event() hangs when m_engine.empty()==true,
timer_wheel_engine offers empty() implement "return 0 == this->m_timer_quantities.m_single_shot_count && 0 == this->m_timer_quantities.m_periodic_count;".

**Comment by eao197** [comment]
@prayforwind 
It seems that you're right. Maybe the info in comments was related to some old versions of timertt. I'll try to update comments with more relevant info.
